var searchData=
[
  ['filecontext_0',['FileContext',['../class_file_data_1_1_file_context.html',1,'FileData']]],
  ['filecontext_2ecs_1',['FileContext.cs',['../_file_context_8cs.html',1,'']]],
  ['filedata_2',['FileData',['../namespace_file_data.html',1,'']]],
  ['filedata_2eassemblyinfo_2ecs_3',['FileData.AssemblyInfo.cs',['../_file_data_8_assembly_info_8cs.html',1,'']]],
  ['filedata_2eglobalusings_2eg_2ecs_4',['FileData.GlobalUsings.g.cs',['../_file_data_8_global_usings_8g_8cs.html',1,'']]],
  ['filedata_3a_3adaos_5',['DAOs',['../namespace_file_data_1_1_d_a_os.html',1,'FileData']]],
  ['font_6',['Using Open Iconic&apos;s Icon Font...',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['fonts_7',['Fonts',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['footprint_20mdash_20ready_20to_20use_20with_20bootstrap_20and_20foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_8',['Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'']]],
  ['for_20code_20samples_20and_20everything_20else_20you_20need_20to_20get_20started_20with_20open_20iconic_20check_20out_20our_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20icons_20a_20and_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20reference_20a_20sections_9',['For code samples and everything else you need to get started with Open Iconic, check out our &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Icons&lt;/a&gt; and &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Reference&lt;/a&gt; sections.',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['foundation_10',['…with Foundation',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['foundation_20a_20href_20https_3a_20github_20com_20iconic_20open_20iconic_20view_20the_20collection_20a_11',['Open Iconic is the open source sibling of &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;Iconic&lt;/a&gt;. It is a hyper-legible collection of 223 icons with a tiny footprint&amp;mdash;ready to use with Bootstrap and Foundation. &lt;a href=&quot;https://github.com/iconic/open-iconic&quot; &gt;View the collection&lt;/a&gt;',['../md__c_1_2_users_2filip_2_rider_projects_2_reddit_2_blazor_2wwwroot_2css_2open-iconic_2_r_e_a_d_m_e.html#autotoc_md0',1,'']]]
];
